---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: godofcontainers/node-mongodb
    tag: '5.11.1'

inputs:
  - name: landscape

outputs:
  - name: built-project

run:
  path: landscape/cf-abacus/etc/concourse/scripts/cf-deploy-build
