---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: godofcontainers/ubuntu-14.04.4-cf
    tag: 'latest'

inputs:
  - name: built-project

run:
  path: built-project/etc/concourse/scripts/cf-deploy-infra
