---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: godofcontainers/ubuntu-14.04.4-cf
    tag: 'latest'

inputs:
  - name: abacus

run:
  path: abacus/etc/concourse/scripts/cf-deploy-infra
