---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: godofcontainers/node-mongodb
    tag: '5.11.1'

inputs:
  - name: abacus
  - name: abacus-config

outputs:
  - name: built-project

run:
  path: abacus/etc/concourse/scripts/cf-deploy-build
