---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: godofcontainers/node-mongodb
    tag: '5.11.1'

inputs:
  - name: built-project

run:
  path: built-project/etc/concourse/scripts/cf-deploy-deploy
