---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: godofcontainers/node-mongodb
    tag: '5.11.1'

inputs:
  - name: abacus

run:
  path: abacus/etc/concourse/scripts/cf-medium-test
