---
resources:
  - name: landscape
    type: git
    source:
      uri: {{landscape-git-repo}}
      branch: {{landscape-git-repo-branch}}
      paths: [cf-abacus,abacus-config]
      private_key: {{landscape-git-repo-private-key}}
      skip-ssl-verification: true

jobs:

################################### CF #########################################

  - name: abacus-deploy
    plan:
      - aggregate:
        - get: landscape
          trigger: true
      - task: build-abacus
        file: landscape/cf-abacus/etc/concourse/tasks/cf-deploy-build.yml
      - task: setup-abacus-infra
        file: built-project/etc/concourse/tasks/cf-deploy-infra.yml
        config:
          params:
            CF_API: {{cf-api}}
            CF_USER: {{cf-user}}
            CF_PASSWORD: {{cf-password}}
            CF_ADMIN_USER: {{cf-admin-user}}
            CF_ADMIN_PASSWORD: {{cf-admin-password}}
            CF_ORG: {{cf-org}}
            CF_SPACE: {{cf-space}}
            CF_DOMAIN: {{cf-domain}}
            UAA_ADMIN: {{uaa-admin}}
            UAA_SECRET: {{uaa-secret}}
            SYSTEM_CLIENT_ID: {{system-client-id}}
            SYSTEM_CLIENT_SECRET: {{system-client-secret}}
            BRIDGE_CLIENT_ID: {{bridge-client-id}}
            BRIDGE_CLIENT_SECRET: {{bridge-client-secret}}
            CF_CLIENT_ID: {{cf-client-id}}
            CF_CLIENT_SECRET: {{cf-client-secret}}
            CONTAINER_CLIENT_ID: {{container-client-id}}
            CONTAINER_CLIENT_SECRET: {{container-client-secret}}
            OBJECT_STORAGE_CLIENT_ID: {{object-storage-client-id}}
            OBJECT_STORAGE_CLIENT_SECRET: {{object-storage-client-secret}}
            HYSTRIX_CLIENT_ID: {{hystrix-client-id}}
            HYSTRIX_CLIENT_SECRET: {{hystrix-client-secret}}
      - task: deploy-abacus
        file: built-project/etc/concourse/tasks/cf-deploy-deploy.yml
        on_failure:
          task: abacus-cleanup
          file: built-project/etc/concourse/tasks/cf-deploy-cleanup.yml
          config:
            params:
              CF_API: {{cf-api}}
              CF_USER: {{cf-user}}
              CF_PASSWORD: {{cf-password}}
              CF_ORG: {{cf-org}}
              CF_SPACE: {{cf-space}}
        config:
          params:
            CF_API: {{cf-api}}
            CF_USER: {{cf-user}}
            CF_PASSWORD: {{cf-password}}
            CF_ADMIN_USER: {{cf-admin-user}}
            CF_ADMIN_PASSWORD: {{cf-admin-password}}
            CF_ORG: {{cf-org}}
            CF_SPACE: {{cf-space}}
            CF_DOMAIN: {{cf-domain}}
            DB_SERVICE_NAME: {{db-service-name}}
            DB_PLAN_NAME: {{db-plan-name}}
            JOBS: 2
      - task: test-abacus
        file: built-project/etc/concourse/tasks/cf-deploy-test.yml
        ensure:
          task: abacus-cleanup
          file: built-project/etc/concourse/tasks/cf-deploy-cleanup.yml
          config:
            params:
              CF_API: {{cf-api}}
              CF_USER: {{cf-user}}
              CF_PASSWORD: {{cf-password}}
              CF_ORG: {{cf-org}}
              CF_SPACE: {{cf-space}}
              FAIL_ON_ERROR: true
        config:
          params:
            CF_API: {{cf-api}}
            CF_DOMAIN: {{cf-domain}}
            SECURED: true
            CLIENT_ID: {{object-storage-client-id}}
            CLIENT_SECRET: {{object-storage-client-secret}}
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
