---
resources:
  - name: abacus
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/cf-abacus.git
      branch: master

jobs:

################################# POUCH ########################################

  - name: pouchdb-5.10
    plan:
      - aggregate:
        - get: abacus
          trigger: true
      - task: build
        config:
          platform: linux
          image: docker:///node#5.10
          inputs:
            - name: abacus
          outputs:
            - name: built-project
          run:
            path: abacus/etc/concourse/scripts/pouch-build
      - task: it
        config:
          platform: linux
          image: docker:///node#5.10
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/pouch-it
          params:
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: demo
        config:
          platform: linux
          image: docker:///node#5.10
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/pouch-demo
          params:
            CI_START_TIMEOUT: 50000
      - task: dupe
        config:
          platform: linux
          image: docker:///node#5.10
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/noop
          params:
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: perf
        config:
          platform: linux
          image: docker:///node#5.10
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/pouch-perf
          params:
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
  - name: pouchdb-4.4
    plan:
      - aggregate:
        - get: abacus
          trigger: true
      - task: build
        config:
          platform: linux
          image: docker:///node#4.4
          inputs:
            - name: abacus
          outputs:
            - name: built-project
          run:
            path: abacus/etc/concourse/scripts/pouch-build
      - task: it
        config:
          platform: linux
          image: docker:///node#4.4
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/pouch-it
          params:
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: demo
        config:
          platform: linux
          image: docker:///node#4.4
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/pouch-demo
          params:
            CI_START_TIMEOUT: 50000
      - task: dupe
        config:
          platform: linux
          image: docker:///node#4.4
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/noop
          params:
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: perf
        config:
          platform: linux
          image: docker:///node#4.4
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/pouch-perf
          params:
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
  - name: pouchdb-0.12
    plan:
      - aggregate:
        - get: abacus
          trigger: true
      - task: build
        config:
          platform: linux
          image: docker:///node#0.12
          inputs:
            - name: abacus
          outputs:
            - name: built-project
          run:
            path: abacus/etc/concourse/scripts/pouch-build
      - task: it
        config:
          platform: linux
          image: docker:///node#0.12
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/pouch-it
          params:
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: demo
        config:
          platform: linux
          image: docker:///node#0.12
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/pouch-demo
          params:
            CI_START_TIMEOUT: 50000
      - task: dupe
        config:
          platform: linux
          image: docker:///node#0.12
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/noop
          params:
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: perf
        config:
          platform: linux
          image: docker:///node#0.12
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/pouch-perf
          params:
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000

################################# COUCH ########################################

  - name: couchdb-5.10
    plan:
      - aggregate:
        - get: abacus
          passed: [pouchdb-5.10]
          trigger: true
      - task: build
        config:
          platform: linux
          image: docker:///godofcontainers/node-couchdb#5.10
          inputs:
            - name: abacus
          outputs:
            - name: built-project
          run:
            path: abacus/etc/concourse/scripts/couch-build
          params:
            JOBS: 1
            DB: http://localhost:5984
      - task: it
        config:
          platform: linux
          image: docker:///godofcontainers/node-couchdb#5.10
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/couch-it
          params:
            JOBS: 1
            DB: http://localhost:5984
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: demo
        config:
          platform: linux
          image: docker:///godofcontainers/node-couchdb#5.10
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/couch-demo
          params:
            JOBS: 1
            DB: http://localhost:5984
            CI_START_TIMEOUT: 50000
      - task: dupe
        config:
          platform: linux
          image: docker:///godofcontainers/node-couchdb#5.10
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/noop
          params:
            JOBS: 1
            DB: http://localhost:5984
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: perf
        config:
          platform: linux
          image: docker:///godofcontainers/node-couchdb#5.10
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/couch-perf
          params:
            JOBS: 1
            DB: http://localhost:5984
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
  - name: couchdb-4.4
    plan:
      - aggregate:
        - get: abacus
          passed: [pouchdb-4.4]
          trigger: true
      - task: build
        config:
          platform: linux
          image: docker:///godofcontainers/node-couchdb#4.4
          inputs:
            - name: abacus
          outputs:
            - name: built-project
          run:
            path: abacus/etc/concourse/scripts/couch-build
          params:
            JOBS: 1
            DB: http://localhost:5984
      - task: it
        config:
          platform: linux
          image: docker:///godofcontainers/node-couchdb#4.4
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/couch-it
          params:
            JOBS: 1
            DB: http://localhost:5984
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: demo
        config:
          platform: linux
          image: docker:///godofcontainers/node-couchdb#4.4
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/couch-demo
          params:
            JOBS: 1
            DB: http://localhost:5984
            CI_START_TIMEOUT: 50000
      - task: dupe
        config:
          platform: linux
          image: docker:///godofcontainers/node-couchdb#4.4
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/noop
          params:
            JOBS: 1
            DB: http://localhost:5984
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: perf
        config:
          platform: linux
          image: docker:///godofcontainers/node-couchdb#4.4
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/couch-perf
          params:
            JOBS: 1
            DB: http://localhost:5984
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
  - name: couchdb-0.12
    plan:
      - aggregate:
        - get: abacus
          passed: [pouchdb-0.12]
          trigger: true
      - task: build
        config:
          platform: linux
          image: docker:///godofcontainers/node-couchdb#0.12
          inputs:
            - name: abacus
          outputs:
            - name: built-project
          run:
            path: abacus/etc/concourse/scripts/couch-build
          params:
            JOBS: 1
            DB: http://localhost:5984
      - task: it
        config:
          platform: linux
          image: docker:///godofcontainers/node-couchdb#0.12
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/couch-it
          params:
            JOBS: 1
            DB: http://localhost:5984
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: demo
        config:
          platform: linux
          image: docker:///godofcontainers/node-couchdb#0.12
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/couch-demo
          params:
            JOBS: 1
            DB: http://localhost:5984
            CI_START_TIMEOUT: 50000
      - task: dupe
        config:
          platform: linux
          image: docker:///godofcontainers/node-couchdb#0.12
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/noop
          params:
            JOBS: 1
            DB: http://localhost:5984
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: perf
        config:
          platform: linux
          image: docker:///godofcontainers/node-couchdb#0.12
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/couch-perf
          params:
            JOBS: 1
            DB: http://localhost:5984
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000

################################# MONGO ########################################

  - name: mongodb-5.10
    plan:
      - aggregate:
        - get: abacus
          passed: [couchdb-5.10]
          trigger: true
      - task: build
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#5.10
          inputs:
            - name: abacus
          outputs:
            - name: built-project
          run:
            path: abacus/etc/concourse/scripts/mongo-build
          params:
            JOBS: 1
            DB: mongodb://localhost:27017
            DBCLIENT: abacus-mongoclient
      - task: it
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#5.10
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/mongo-it
          params:
            JOBS: 1
            DB: mongodb://localhost:27017
            DBCLIENT: abacus-mongoclient
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: demo
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#5.10
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/mongo-demo
          params:
            JOBS: 1
            DB: mongodb://localhost:27017
            DBCLIENT: abacus-mongoclient
            CI_START_TIMEOUT: 50000
      - task: dupe
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#5.10
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/noop
          params:
            JOBS: 1
            DB: mongodb://localhost:27017
            DBCLIENT: abacus-mongoclient
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: perf
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#5.10
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/mongo-perf
          params:
            JOBS: 1
            DB: mongodb://localhost:27017
            DBCLIENT: abacus-mongoclient
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
  - name: mongodb-4.4
    plan:
      - aggregate:
        - get: abacus
          passed: [couchdb-4.4]
          trigger: true
      - task: build
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#4.4
          inputs:
            - name: abacus
          outputs:
            - name: built-project
          run:
            path: abacus/etc/concourse/scripts/mongo-build
          params:
            JOBS: 1
            DB: mongodb://localhost:27017
            DBCLIENT: abacus-mongoclient
      - task: it
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#4.4
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/mongo-it
          params:
            JOBS: 1
            DB: mongodb://localhost:27017
            DBCLIENT: abacus-mongoclient
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: demo
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#4.4
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/mongo-demo
          params:
            JOBS: 1
            DB: mongodb://localhost:27017
            DBCLIENT: abacus-mongoclient
            CI_START_TIMEOUT: 50000
      - task: dupe
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#4.4
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/noop
          params:
            JOBS: 1
            DB: mongodb://localhost:27017
            DBCLIENT: abacus-mongoclient
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: perf
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#4.4
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/mongo-perf
          params:
            JOBS: 1
            DB: mongodb://localhost:27017
            DBCLIENT: abacus-mongoclient
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
  - name: mongodb-0.12
    plan:
      - aggregate:
        - get: abacus
          passed: [couchdb-0.12]
          trigger: true
      - task: build
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#0.12
          inputs:
            - name: abacus
          outputs:
            - name: built-project
          run:
            path: abacus/etc/concourse/scripts/mongo-build
          params:
            JOBS: 1
            DB: mongodb://localhost:27017
            DBCLIENT: abacus-mongoclient
      - task: it
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#0.12
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/mongo-it
          params:
            JOBS: 1
            DB: mongodb://localhost:27017
            DBCLIENT: abacus-mongoclient
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: demo
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#0.12
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/mongo-demo
          params:
            JOBS: 1
            DB: mongodb://localhost:27017
            DBCLIENT: abacus-mongoclient
            CI_START_TIMEOUT: 50000
      - task: dupe
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#0.12
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/noop
          params:
            JOBS: 1
            DB: mongodb://localhost:27017
            DBCLIENT: abacus-mongoclient
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
      - task: perf
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#0.12
          inputs:
            - name: built-project
          run:
            path: built-project/etc/concourse/scripts/mongo-perf
          params:
            JOBS: 1
            DB: mongodb://localhost:27017
            DBCLIENT: abacus-mongoclient
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000

################################### CF #########################################

  - name: cf-medium
    plan:
      - aggregate:
        - get: abacus
          passed: [mongodb-0.12,mongodb-4.4,mongodb-5.10]
          trigger: true
      - task: infra
        config:
          platform: linux
          image: docker:///godofcontainers/ubuntu-14.04.4-cf#latest
          inputs:
            - name: abacus
          run:
            path: abacus/etc/concourse/scripts/cf-setup
          params:
            CF_API: {{cf-api}}
            CF_USER: {{cf-user}}
            CF_PASSWORD: {{cf-password}}
            CF_ADMIN_USER: {{cf-admin-password}}
            CF_ADMIN_PASSWORD: {{cf-admin-password}}
            CF_ORG: {{cf-org}}
            CF_SPACE: {{cf-space}}
            CF_DOMAIN: {{cf-domain}}
      - task: deploy
        config:
          platform: linux
          image: docker:///godofcontainers/node-mongodb#5.10
          inputs:
            - name: abacus
          run:
            path: abacus/etc/concourse/scripts/cf-test
          params:
            CF_TEST: true
            JOBS: 2
            CF_API: {{cf-api}}
            CF_USER: {{cf-user}}
            CF_PASSWORD: {{cf-password}}
            CF_ORG: {{cf-org}}
            CF_SPACE: {{cf-space}}
            CF_DOMAIN: {{cf-domain}}
            CI_START_TIMEOUT: 50000
            CI_PIPELINE_TIMEOUT: 100000
